<?php

use Illuminate\Database\Seeder;

class ProvinceAndCountySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $provinces = collect([
            1 => 'Adana',
            2 => 'Adıyaman',
            3 => 'Afyonkarahisar',
            4 => 'Ağrı',
            5 => 'Amasya',
            6 => 'Ankara',
            7 => 'Antalya',
            8 => 'Artvin',
            9 => 'Aydın',
            10 => 'Balıkesir',
            11 => 'Bilecik',
            12 => 'Bingöl',
            13 => 'Bitlis',
            14 => 'Bolu',
            15 => 'Burdur',
            16 => 'Bursa',
            17 => 'Çanakkale',
            18 => 'Çankırı',
            19 => 'Çorum',
            20 => 'Denizli',
            21 => 'Diyarbakır',
            22 => 'Edirne',
            23 => 'Elâzığ',
            24 => 'Erzincan',
            25 => 'Erzurum',
            26 => 'Eskişehir',
            27 => 'Gaziantep',
            28 => 'Giresun',
            29 => 'Gümüşhane',
            30 => 'Hakkâri',
            31 => 'Hatay',
            32 => 'Isparta',
            33 => 'Mersin',
            34 => 'İstanbul',
            35 => 'İzmir',
            36 => 'Kars',
            37 => 'Kastamonu',
            38 => 'Kayseri',
            39 => 'Kırklareli',
            40 => 'Kırşehir',
            41 => 'Kocaeli',
            42 => 'Konya',
            43 => 'Kütahya',
            44 => 'Malatya',
            45 => 'Manisa',
            46 => 'Kahramanmaraş',
            47 => 'Mardin',
            48 => 'Muğla',
            49 => 'Muş',
            50 => 'Nevşehir',
            51 => 'Niğde',
            52 => 'Ordu',
            53 => 'Rize',
            54 => 'Sakarya',
            55 => 'Samsun',
            56 => 'Siirt',
            57 => 'Sinop',
            58 => 'Sivas',
            59 => 'Tekirdağ',
            60 => 'Tokat',
            61 => 'Trabzon',
            62 => 'Tunceli',
            63 => 'Şanlıurfa',
            64 => 'Uşak',
            65 => 'Van',
            66 => 'Yozgat',
            67 => 'Zonguldak',
            68 => 'Aksaray',
            69 => 'Bayburt',
            70 => 'Karaman',
            71 => 'Kırıkkale',
            72 => 'Batman',
            73 => 'Şırnak',
            74 => 'Bartın',
            75 => 'Ardahan',
            76 => 'Iğdır',
            77 => 'Yalova',
            78 => 'Karabük',
            79 => 'Kilis',
            80 => 'Osmaniye',
            81 => 'Düzce'
        ]);

        $counties = collect([
            ['name' => 'Abana', 'province' => 37],
            ['name' => 'Acıgöl', 'province' => 50],
            ['name' => 'Acıpayam', 'province' => 20],
            ['name' => 'Adaklı', 'province' => 12],
            ['name' => 'Adalar', 'province' => 34],
            ['name' => 'Adapazarı', 'province' => 54],
            ['name' => 'Adıyaman', 'province' => 2],
            ['name' => 'Adilcevaz', 'province' => 13],
            ['name' => 'Afşin', 'province' => 46],
            ['name' => 'Afyonkarahisar', 'province' => 3],
            ['name' => 'Ağaçören', 'province' => 68],
            ['name' => 'Ağın', 'province' => 23],
            ['name' => 'Ağlasun', 'province' => 15],
            ['name' => 'Ağlı', 'province' => 37],
            ['name' => 'Ağrı', 'province' => 4],
            ['name' => 'Ahırlı', 'province' => 42],
            ['name' => 'Ahlat', 'province' => 13],
            ['name' => 'Ahmetli', 'province' => 45],
            ['name' => 'Akçaabat', 'province' => 61],
            ['name' => 'Akçadağ', 'province' => 44],
            ['name' => 'Akçakale', 'province' => 63],
            ['name' => 'Akçakent', 'province' => 40],
            ['name' => 'Akçakoca', 'province' => 81],
            ['name' => 'Akdağmadeni', 'province' => 66],
            ['name' => 'Akdeniz', 'province' => 33],
            ['name' => 'Akhisar', 'province' => 45],
            ['name' => 'Akıncılar', 'province' => 58],
            ['name' => 'Akkışla', 'province' => 38],
            ['name' => 'Akkuş', 'province' => 52],
            ['name' => 'Akören', 'province' => 42],
            ['name' => 'Akpınar', 'province' => 40],
            ['name' => 'Aksaray', 'province' => 68],
            ['name' => 'Akseki', 'province' => 7],
            ['name' => 'Aksu', 'province' => 7],
            ['name' => 'Aksu', 'province' => 32],
            ['name' => 'Akşehir', 'province' => 42],
            ['name' => 'Akyaka', 'province' => 36],
            ['name' => 'Akyazı', 'province' => 54],
            ['name' => 'Akyurt', 'province' => 6],
            ['name' => 'Alaca', 'province' => 19],
            ['name' => 'Alacakaya', 'province' => 23],
            ['name' => 'Alaçam', 'province' => 55],
            ['name' => 'Aladağ', 'province' => 1],
            ['name' => 'Alanya', 'province' => 7],
            ['name' => 'Alaplı', 'province' => 67],
            ['name' => 'Alaşehir', 'province' => 45],
            ['name' => 'Aliağa', 'province' => 35],
            ['name' => 'Almus', 'province' => 60],
            ['name' => 'Alpu', 'province' => 26],
            ['name' => 'Altıeylül', 'province' => 10],
            ['name' => 'Altındağ', 'province' => 6],
            ['name' => 'Altınekin', 'province' => 42],
            ['name' => 'Altınordu', 'province' => 52],
            ['name' => 'Altınova', 'province' => 77],
            ['name' => 'Altınözü', 'province' => 31],
            ['name' => 'Altıntaş', 'province' => 43],
            ['name' => 'Altınyayla', 'province' => 15],
            ['name' => 'Altınyayla', 'province' => 58],
            ['name' => 'Altunhisar', 'province' => 51],
            ['name' => 'Alucra', 'province' => 28],
            ['name' => 'Amasra', 'province' => 74],
            ['name' => 'Amasya', 'province' => 5],
            ['name' => 'Anamur', 'province' => 33],
            ['name' => 'Andırın', 'province' => 46],
            ['name' => 'Antakya', 'province' => 31],
            ['name' => 'Araban', 'province' => 27],
            ['name' => 'Araç', 'province' => 37],
            ['name' => 'Araklı', 'province' => 61],
            ['name' => 'Aralık', 'province' => 76],
            ['name' => 'Arapgir', 'province' => 44],
            ['name' => 'Ardahan', 'province' => 75],
            ['name' => 'Ardanuç', 'province' => 8],
            ['name' => 'Ardeşen', 'province' => 53],
            ['name' => 'Arguvan', 'province' => 44],
            ['name' => 'Arhavi', 'province' => 8],
            ['name' => 'Arıcak', 'province' => 23],
            ['name' => 'Arifiye', 'province' => 54],
            ['name' => 'Armutlu', 'province' => 77],
            ['name' => 'Arnavutköy', 'province' => 34],
            ['name' => 'Arpaçay', 'province' => 36],
            ['name' => 'Arsin', 'province' => 61],
            ['name' => 'Arsuz', 'province' => 31],
            ['name' => 'Artova', 'province' => 60],
            ['name' => 'Artuklu', 'province' => 47],
            ['name' => 'Artvin', 'province' => 8],
            ['name' => 'Asarcık', 'province' => 55],
            ['name' => 'Aslanapa', 'province' => 43],
            ['name' => 'Aşkale', 'province' => 25],
            ['name' => 'Atabey', 'province' => 32],
            ['name' => 'Atakum', 'province' => 55],
            ['name' => 'Ataşehir', 'province' => 34],
            ['name' => 'Atkaracalar', 'province' => 18],
            ['name' => 'Avanos', 'province' => 50],
            ['name' => 'Avcılar', 'province' => 34],
            ['name' => 'Ayancık', 'province' => 57],
            ['name' => 'Ayaş', 'province' => 6],
            ['name' => 'Aybastı', 'province' => 52],
            ['name' => 'Aydıncık', 'province' => 33],
            ['name' => 'Aydıncık', 'province' => 66],
            ['name' => 'Aydıntepe', 'province' => 69],
            ['name' => 'Ayrancı', 'province' => 70],
            ['name' => 'Ayvacık', 'province' => 17],
            ['name' => 'Ayvacık', 'province' => 55],
            ['name' => 'Ayvalık', 'province' => 10],
            ['name' => 'Azdavay', 'province' => 37],
            ['name' => 'Aziziye', 'province' => 25],
            ['name' => 'Babadağ', 'province' => 20],
            ['name' => 'Babaeski', 'province' => 39],
            ['name' => 'Bafra', 'province' => 55],
            ['name' => 'Bağcılar', 'province' => 34],
            ['name' => 'Bağlar', 'province' => 21],
            ['name' => 'Bahçe', 'province' => 80],
            ['name' => 'Bahçelievler', 'province' => 34],
            ['name' => 'Bahçesaray', 'province' => 65],
            ['name' => 'Bahşili', 'province' => 71],
            ['name' => 'Bakırköy', 'province' => 34],
            ['name' => 'Baklan', 'province' => 20],
            ['name' => 'Bala', 'province' => 6],
            ['name' => 'Balçova', 'province' => 35],
            ['name' => 'Balışeyh', 'province' => 71],
            ['name' => 'Balya', 'province' => 10],
            ['name' => 'Banaz', 'province' => 64],
            ['name' => 'Bandırma', 'province' => 10],
            ['name' => 'Bartın', 'province' => 74],
            ['name' => 'Baskil', 'province' => 23],
            ['name' => 'Başakşehir', 'province' => 34],
            ['name' => 'Başçiftlik', 'province' => 60],
            ['name' => 'Başiskele', 'province' => 41],
            ['name' => 'Başkale', 'province' => 65],
            ['name' => 'Başmakçı', 'province' => 3],
            ['name' => 'Başyayla', 'province' => 70],
            ['name' => 'Batman', 'province' => 72],
            ['name' => 'Battalgazi', 'province' => 44],
            ['name' => 'Bayat', 'province' => 3],
            ['name' => 'Bayat', 'province' => 19],
            ['name' => 'Bayburt', 'province' => 69],
            ['name' => 'Bayındır', 'province' => 35],
            ['name' => 'Baykan', 'province' => 56],
            ['name' => 'Bayraklı', 'province' => 35],
            ['name' => 'Bayramiç', 'province' => 17],
            ['name' => 'Bayramören', 'province' => 18],
            ['name' => 'Bayrampaşa', 'province' => 34],
            ['name' => 'Bekilli', 'province' => 20],
            ['name' => 'Belen', 'province' => 31],
            ['name' => 'Bergama', 'province' => 35],
            ['name' => 'Besni', 'province' => 2],
            ['name' => 'Beşikdüzü', 'province' => 61],
            ['name' => 'Beşiktaş', 'province' => 34],
            ['name' => 'Beşiri', 'province' => 72],
            ['name' => 'Beyağaç', 'province' => 20],
            ['name' => 'Beydağ', 'province' => 35],
            ['name' => 'Beykoz', 'province' => 34],
            ['name' => 'Beylikdüzü', 'province' => 34],
            ['name' => 'Beylikova', 'province' => 26],
            ['name' => 'Beyoğlu', 'province' => 34],
            ['name' => 'Beypazarı', 'province' => 6],
            ['name' => 'Beyşehir', 'province' => 42],
            ['name' => 'Beytüşşebap', 'province' => 73],
            ['name' => 'Biga', 'province' => 17],
            ['name' => 'Bigadiç', 'province' => 10],
            ['name' => 'Bilecik', 'province' => 11],
            ['name' => 'Bingöl', 'province' => 12],
            ['name' => 'Birecik', 'province' => 63],
            ['name' => 'Bismil', 'province' => 21],
            ['name' => 'Bitlis', 'province' => 13],
            ['name' => 'Bodrum', 'province' => 48],
            ['name' => 'Boğazkale', 'province' => 19],
            ['name' => 'Boğazlıyan', 'province' => 66],
            ['name' => 'Bolu', 'province' => 14],
            ['name' => 'Bolvadin', 'province' => 3],
            ['name' => 'Bor', 'province' => 51],
            ['name' => 'Borçka', 'province' => 8],
            ['name' => 'Bornova', 'province' => 35],
            ['name' => 'Boyabat', 'province' => 57],
            ['name' => 'Bozcaada', 'province' => 17],
            ['name' => 'Bozdoğan', 'province' => 9],
            ['name' => 'Bozkır', 'province' => 42],
            ['name' => 'Bozkurt', 'province' => 20],
            ['name' => 'Bozkurt', 'province' => 37],
            ['name' => 'Bozova', 'province' => 63],
            ['name' => 'Boztepe', 'province' => 40],
            ['name' => 'Bozüyük', 'province' => 11],
            ['name' => 'Bozyazı', 'province' => 33],
            ['name' => 'Buca', 'province' => 35],
            ['name' => 'Bucak', 'province' => 15],
            ['name' => 'Buharkent', 'province' => 9],
            ['name' => 'Bulancak', 'province' => 28],
            ['name' => 'Bulanık', 'province' => 49],
            ['name' => 'Buldan', 'province' => 20],
            ['name' => 'Burdur', 'province' => 15],
            ['name' => 'Burhaniye', 'province' => 10],
            ['name' => 'Bünyan', 'province' => 38],
            ['name' => 'Büyükçekmece', 'province' => 34],
            ['name' => 'Büyükorhan', 'province' => 16],
            ['name' => 'Canik', 'province' => 55],
            ['name' => 'Ceyhan', 'province' => 1],
            ['name' => 'Ceylanpınar', 'province' => 63],
            ['name' => 'Cide', 'province' => 37],
            ['name' => 'Cihanbeyli', 'province' => 42],
            ['name' => 'Cizre', 'province' => 73],
            ['name' => 'Cumayeri', 'province' => 81],
            ['name' => 'Çağlayancerit', 'province' => 46],
            ['name' => 'Çal', 'province' => 20],
            ['name' => 'Çaldıran', 'province' => 65],
            ['name' => 'Çamardı', 'province' => 51],
            ['name' => 'Çamaş', 'province' => 52],
            ['name' => 'Çameli', 'province' => 20],
            ['name' => 'Çamlıdere', 'province' => 6],
            ['name' => 'Çamlıhemşin', 'province' => 53],
            ['name' => 'Çamlıyayla', 'province' => 33],
            ['name' => 'Çamoluk', 'province' => 28],
            ['name' => 'Çan', 'province' => 17],
            ['name' => 'Çanakçı', 'province' => 28],
            ['name' => 'Çanakkale', 'province' => 17],
            ['name' => 'Çandır', 'province' => 66],
            ['name' => 'Çankaya', 'province' => 6],
            ['name' => 'Çankırı', 'province' => 18],
            ['name' => 'Çardak', 'province' => 20],
            ['name' => 'Çarşamba', 'province' => 55],
            ['name' => 'Çarşıbaşı', 'province' => 61],
            ['name' => 'Çat', 'province' => 25],
            ['name' => 'Çatak', 'province' => 65],
            ['name' => 'Çatalca', 'province' => 34],
            ['name' => 'Çatalpınar', 'province' => 52],
            ['name' => 'Çatalzeytin', 'province' => 37],
            ['name' => 'Çavdarhisar', 'province' => 43],
            ['name' => 'Çavdır', 'province' => 15],
            ['name' => 'Çay', 'province' => 3],
            ['name' => 'Çaybaşı', 'province' => 52],
            ['name' => 'Çaycuma', 'province' => 67],
            ['name' => 'Çayeli', 'province' => 53],
            ['name' => 'Çayıralan', 'province' => 66],
            ['name' => 'Çayırlı', 'province' => 24],
            ['name' => 'Çayırova', 'province' => 41],
            ['name' => 'Çaykara', 'province' => 61],
            ['name' => 'Çekerek', 'province' => 66],
            ['name' => 'Çekmeköy', 'province' => 34],
            ['name' => 'Çelebi', 'province' => 71],
            ['name' => 'Çelikhan', 'province' => 2],
            ['name' => 'Çeltik', 'province' => 42],
            ['name' => 'Çeltikçi', 'province' => 15],
            ['name' => 'Çemişgezek', 'province' => 62],
            ['name' => 'Çerkeş', 'province' => 18],
            ['name' => 'Çerkezköy', 'province' => 59],
            ['name' => 'Çermik', 'province' => 21],
            ['name' => 'Çeşme', 'province' => 35],
            ['name' => 'Çıldır', 'province' => 75],
            ['name' => 'Çınar', 'province' => 21],
            ['name' => 'Çınarcık', 'province' => 77],
            ['name' => 'Çiçekdağı', 'province' => 40],
            ['name' => 'Çifteler', 'province' => 26],
            ['name' => 'Çiftlik', 'province' => 51],
            ['name' => 'Çiftlikköy', 'province' => 77],
            ['name' => 'Çiğli', 'province' => 35],
            ['name' => 'Çilimli', 'province' => 81],
            ['name' => 'Çine', 'province' => 9],
            ['name' => 'Çivril', 'province' => 20],
            ['name' => 'Çobanlar', 'province' => 3],
            ['name' => 'Çorlu', 'province' => 59],
            ['name' => 'Çorum', 'province' => 19],
            ['name' => 'Çubuk', 'province' => 6],
            ['name' => 'Çukurca', 'province' => 30],
            ['name' => 'Çukurova', 'province' => 1],
            ['name' => 'Çumra', 'province' => 42],
            ['name' => 'Çüngüş', 'province' => 21],
            ['name' => 'Daday', 'province' => 37],
            ['name' => 'Dalaman', 'province' => 48],
            ['name' => 'Damal', 'province' => 75],
            ['name' => 'Darende', 'province' => 44],
            ['name' => 'Dargeçit', 'province' => 47],
            ['name' => 'Darıca', 'province' => 41],
            ['name' => 'Datça', 'province' => 48],
            ['name' => 'Dazkırı', 'province' => 3],
            ['name' => 'Defne', 'province' => 31],
            ['name' => 'Delice', 'province' => 71],
            ['name' => 'Demirci', 'province' => 45],
            ['name' => 'Demirköy', 'province' => 39],
            ['name' => 'Demirözü', 'province' => 69],
            ['name' => 'Demre', 'province' => 7],
            ['name' => 'Derbent', 'province' => 42],
            ['name' => 'Derebucak', 'province' => 42],
            ['name' => 'Dereli', 'province' => 28],
            ['name' => 'Derepazarı', 'province' => 53],
            ['name' => 'Derik', 'province' => 47],
            ['name' => 'Derince', 'province' => 41],
            ['name' => 'Derinkuyu', 'province' => 50],
            ['name' => 'Dernekpazarı', 'province' => 61],
            ['name' => 'Develi', 'province' => 38],
            ['name' => 'Devrek', 'province' => 67],
            ['name' => 'Devrekani', 'province' => 37],
            ['name' => 'Dicle', 'province' => 21],
            ['name' => 'Didim', 'province' => 9],
            ['name' => 'Digor', 'province' => 36],
            ['name' => 'Dikili', 'province' => 35],
            ['name' => 'Dikmen', 'province' => 57],
            ['name' => 'Dilovası', 'province' => 41],
            ['name' => 'Dinar', 'province' => 3],
            ['name' => 'Divriği', 'province' => 58],
            ['name' => 'Diyadin', 'province' => 4],
            ['name' => 'Dodurga', 'province' => 19],
            ['name' => 'Doğanhisar', 'province' => 42],
            ['name' => 'Doğankent', 'province' => 28],
            ['name' => 'Doğanşar', 'province' => 58],
            ['name' => 'Doğanşehir', 'province' => 44],
            ['name' => 'Doğanyol', 'province' => 44],
            ['name' => 'Doğanyurt', 'province' => 37],
            ['name' => 'Doğubayazıt', 'province' => 4],
            ['name' => 'Domaniç', 'province' => 43],
            ['name' => 'Dörtdivan', 'province' => 14],
            ['name' => 'Dörtyol', 'province' => 31],
            ['name' => 'Döşemealtı', 'province' => 7],
            ['name' => 'Dulkadiroğlu', 'province' => 46],
            ['name' => 'Dumlupınar', 'province' => 43],
            ['name' => 'Durağan', 'province' => 57],
            ['name' => 'Dursunbey', 'province' => 10],
            ['name' => 'Düzce', 'province' => 81],
            ['name' => 'Düziçi', 'province' => 80],
            ['name' => 'Düzköy', 'province' => 61],
            ['name' => 'Eceabat', 'province' => 17],
            ['name' => 'Edirne', 'province' => 22],
            ['name' => 'Edremit', 'province' => 10],
            ['name' => 'Edremit', 'province' => 65],
            ['name' => 'Efeler', 'province' => 9],
            ['name' => 'Eflani', 'province' => 78],
            ['name' => 'Eğil', 'province' => 21],
            ['name' => 'Eğirdir', 'province' => 32],
            ['name' => 'Ekinözü', 'province' => 46],
            ['name' => 'Elazığ', 'province' => 23],
            ['name' => 'Elbeyli', 'province' => 79],
            ['name' => 'Elbistan', 'province' => 46],
            ['name' => 'Eldivan', 'province' => 18],
            ['name' => 'Eleşkirt', 'province' => 4],
            ['name' => 'Elmadağ', 'province' => 6],
            ['name' => 'Elmalı', 'province' => 7],
            ['name' => 'Emet', 'province' => 43],
            ['name' => 'Emirdağ', 'province' => 3],
            ['name' => 'Emirgazi', 'province' => 42],
            ['name' => 'Enez', 'province' => 22],
            ['name' => 'Erbaa', 'province' => 60],
            ['name' => 'Erciş', 'province' => 65],
            ['name' => 'Erdek', 'province' => 10],
            ['name' => 'Erdemli', 'province' => 33],
            ['name' => 'Ereğli', 'province' => 42],
            ['name' => 'Ereğli', 'province' => 67],
            ['name' => 'Erenler', 'province' => 54],
            ['name' => 'Erfelek', 'province' => 57],
            ['name' => 'Ergani', 'province' => 21],
            ['name' => 'Ergene', 'province' => 59],
            ['name' => 'Ermenek', 'province' => 70],
            ['name' => 'Eruh', 'province' => 56],
            ['name' => 'Erzin', 'province' => 31],
            ['name' => 'Erzincan', 'province' => 24],
            ['name' => 'Esenler', 'province' => 34],
            ['name' => 'Esenyurt', 'province' => 34],
            ['name' => 'Eskil', 'province' => 68],
            ['name' => 'Eskipazar', 'province' => 78],
            ['name' => 'Espiye', 'province' => 28],
            ['name' => 'Eşme', 'province' => 64],
            ['name' => 'Etimesgut', 'province' => 6],
            ['name' => 'Evciler', 'province' => 3],
            ['name' => 'Evren', 'province' => 6],
            ['name' => 'Eynesil', 'province' => 28],
            ['name' => 'Eyüp', 'province' => 34],
            ['name' => 'Eyyübiye', 'province' => 63],
            ['name' => 'Ezine', 'province' => 17],
            ['name' => 'Fatih', 'province' => 34],
            ['name' => 'Fatsa', 'province' => 52],
            ['name' => 'Feke', 'province' => 1],
            ['name' => 'Felahiye', 'province' => 38],
            ['name' => 'Ferizli', 'province' => 54],
            ['name' => 'Fethiye', 'province' => 48],
            ['name' => 'Fındıklı', 'province' => 53],
            ['name' => 'Finike', 'province' => 7],
            ['name' => 'Foça', 'province' => 35],
            ['name' => 'Gaziemir', 'province' => 35],
            ['name' => 'Gaziosmanpaşa', 'province' => 34],
            ['name' => 'Gazipaşa', 'province' => 7],
            ['name' => 'Gebze', 'province' => 41],
            ['name' => 'Gediz', 'province' => 43],
            ['name' => 'Gelendost', 'province' => 32],
            ['name' => 'Gelibolu', 'province' => 17],
            ['name' => 'Gemerek', 'province' => 58],
            ['name' => 'Gemlik', 'province' => 16],
            ['name' => 'Genç', 'province' => 12],
            ['name' => 'Gercüş', 'province' => 72],
            ['name' => 'Gerede', 'province' => 14],
            ['name' => 'Gerger', 'province' => 2],
            ['name' => 'Germencik', 'province' => 9],
            ['name' => 'Gerze', 'province' => 57],
            ['name' => 'Gevaş', 'province' => 65],
            ['name' => 'Geyve', 'province' => 54],
            ['name' => 'Giresun', 'province' => 28],
            ['name' => 'Gökçeada', 'province' => 17],
            ['name' => 'Gökçebey', 'province' => 67],
            ['name' => 'Göksun', 'province' => 46],
            ['name' => 'Gölbaşı', 'province' => 2],
            ['name' => 'Gölbaşı', 'province' => 6],
            ['name' => 'Gölcük', 'province' => 41],
            ['name' => 'Göle', 'province' => 75],
            ['name' => 'Gölhisar', 'province' => 15],
            ['name' => 'Gölköy', 'province' => 52],
            ['name' => 'Gölmarmara', 'province' => 45],
            ['name' => 'Gölova', 'province' => 58],
            ['name' => 'Gölpazarı', 'province' => 11],
            ['name' => 'Gölyaka', 'province' => 81],
            ['name' => 'Gömeç', 'province' => 10],
            ['name' => 'Gönen', 'province' => 10],
            ['name' => 'Gönen', 'province' => 32],
            ['name' => 'Gördes', 'province' => 45],
            ['name' => 'Görele', 'province' => 28],
            ['name' => 'Göynücek', 'province' => 5],
            ['name' => 'Göynük', 'province' => 14],
            ['name' => 'Güce', 'province' => 28],
            ['name' => 'Güçlükonak', 'province' => 73],
            ['name' => 'Güdül', 'province' => 6],
            ['name' => 'Gülağaç', 'province' => 68],
            ['name' => 'Gülnar', 'province' => 33],
            ['name' => 'Gülşehir', 'province' => 50],
            ['name' => 'Gülyalı', 'province' => 52],
            ['name' => 'Gümüşhacıköy', 'province' => 5],
            ['name' => 'Gümüşhane', 'province' => 29],
            ['name' => 'Gümüşova', 'province' => 81],
            ['name' => 'Gündoğmuş', 'province' => 7],
            ['name' => 'Güney', 'province' => 20],
            ['name' => 'Güneysınır', 'province' => 42],
            ['name' => 'Güneysu', 'province' => 53],
            ['name' => 'Güngören', 'province' => 34],
            ['name' => 'Günyüzü', 'province' => 26],
            ['name' => 'Gürgentepe', 'province' => 52],
            ['name' => 'Güroymak', 'province' => 13],
            ['name' => 'Gürpınar', 'province' => 65],
            ['name' => 'Gürsu', 'province' => 16],
            ['name' => 'Gürün', 'province' => 58],
            ['name' => 'Güzelbahçe', 'province' => 35],
            ['name' => 'Güzelyurt', 'province' => 68],
            ['name' => 'Hacıbektaş', 'province' => 50],
            ['name' => 'Hacılar', 'province' => 38],
            ['name' => 'Hadim', 'province' => 42],
            ['name' => 'Hafik', 'province' => 58],
            ['name' => 'Hakkâri', 'province' => 30],
            ['name' => 'Halfeti', 'province' => 63],
            ['name' => 'Haliliye', 'province' => 63],
            ['name' => 'Halkapınar', 'province' => 42],
            ['name' => 'Hamamözü', 'province' => 5],
            ['name' => 'Hamur', 'province' => 4],
            ['name' => 'Han', 'province' => 26],
            ['name' => 'Hanak', 'province' => 75],
            ['name' => 'Hani', 'province' => 21],
            ['name' => 'Hanönü', 'province' => 37],
            ['name' => 'Harmancık', 'province' => 16],
            ['name' => 'Harran', 'province' => 63],
            ['name' => 'Hasanbeyli', 'province' => 80],
            ['name' => 'Hasankeyf', 'province' => 72],
            ['name' => 'Hasköy', 'province' => 49],
            ['name' => 'Hassa', 'province' => 31],
            ['name' => 'Havran', 'province' => 10],
            ['name' => 'Havsa', 'province' => 22],
            ['name' => 'Havza', 'province' => 55],
            ['name' => 'Haymana', 'province' => 6],
            ['name' => 'Hayrabolu', 'province' => 59],
            ['name' => 'Hayrat', 'province' => 61],
            ['name' => 'Hazro', 'province' => 21],
            ['name' => 'Hekimhan', 'province' => 44],
            ['name' => 'Hemşin', 'province' => 53],
            ['name' => 'Hendek', 'province' => 54],
            ['name' => 'Hınıs', 'province' => 25],
            ['name' => 'Hilvan', 'province' => 63],
            ['name' => 'Hisarcık', 'province' => 43],
            ['name' => 'Hizan', 'province' => 13],
            ['name' => 'Hocalar', 'province' => 3],
            ['name' => 'Honaz', 'province' => 20],
            ['name' => 'Hopa', 'province' => 8],
            ['name' => 'Horasan', 'province' => 25],
            ['name' => 'Hozat', 'province' => 62],
            ['name' => 'Hüyük', 'province' => 42],
            ['name' => 'Iğdır', 'province' => 76],
            ['name' => 'Ilgaz', 'province' => 18],
            ['name' => 'Ilgın', 'province' => 42],
            ['name' => 'Isparta', 'province' => 32],
            ['name' => 'İbradı', 'province' => 7],
            ['name' => 'İdil', 'province' => 73],
            ['name' => 'İhsangazi', 'province' => 37],
            ['name' => 'İhsaniye', 'province' => 3],
            ['name' => 'İkizce', 'province' => 52],
            ['name' => 'İkizdere', 'province' => 53],
            ['name' => 'İliç', 'province' => 24],
            ['name' => 'İlkadım', 'province' => 55],
            ['name' => 'İmamoğlu', 'province' => 1],
            ['name' => 'İmranlı', 'province' => 58],
            ['name' => 'İncesu', 'province' => 38],
            ['name' => 'İncirliova', 'province' => 9],
            ['name' => 'İnebolu', 'province' => 37],
            ['name' => 'İnegöl', 'province' => 16],
            ['name' => 'İnhisar', 'province' => 11],
            ['name' => 'İnönü', 'province' => 26],
            ['name' => 'İpekyolu', 'province' => 65],
            ['name' => 'İpsala', 'province' => 22],
            ['name' => 'İscehisar', 'province' => 3],
            ['name' => 'İskenderun', 'province' => 31],
            ['name' => 'İskilip', 'province' => 19],
            ['name' => 'İslahiye', 'province' => 27],
            ['name' => 'İspir', 'province' => 25],
            ['name' => 'İvrindi', 'province' => 10],
            ['name' => 'İyidere', 'province' => 53],
            ['name' => 'İzmit', 'province' => 41],
            ['name' => 'İznik', 'province' => 16],
            ['name' => 'Kabadüz', 'province' => 52],
            ['name' => 'Kabataş', 'province' => 52],
            ['name' => 'Kadıköy', 'province' => 34],
            ['name' => 'Kadınhanı', 'province' => 42],
            ['name' => 'Kadışehri', 'province' => 66],
            ['name' => 'Kadirli', 'province' => 80],
            ['name' => 'Kağıthane', 'province' => 34],
            ['name' => 'Kağızman', 'province' => 36],
            ['name' => 'Kahta', 'province' => 2],
            ['name' => 'Kale', 'province' => 20],
            ['name' => 'Kale', 'province' => 44],
            ['name' => 'Kalecik', 'province' => 6],
            ['name' => 'Kalkandere', 'province' => 53],
            ['name' => 'Kaman', 'province' => 40],
            ['name' => 'Kandıra', 'province' => 41],
            ['name' => 'Kangal', 'province' => 58],
            ['name' => 'Kapaklı', 'province' => 59],
            ['name' => 'Karabağlar', 'province' => 35],
            ['name' => 'Karaburun', 'province' => 35],
            ['name' => 'Karabük', 'province' => 78],
            ['name' => 'Karacabey', 'province' => 16],
            ['name' => 'Karacasu', 'province' => 9],
            ['name' => 'Karaçoban', 'province' => 25],
            ['name' => 'Karahallı', 'province' => 64],
            ['name' => 'Karaisalı', 'province' => 1],
            ['name' => 'Karakeçili', 'province' => 71],
            ['name' => 'Karakoçan', 'province' => 23],
            ['name' => 'Karakoyunlu', 'province' => 76],
            ['name' => 'Karaköprü', 'province' => 63],
            ['name' => 'Karaman', 'province' => 70],
            ['name' => 'Karamanlı', 'province' => 15],
            ['name' => 'Karamürsel', 'province' => 41],
            ['name' => 'Karapınar', 'province' => 42],
            ['name' => 'Karapürçek', 'province' => 54],
            ['name' => 'Karasu', 'province' => 54],
            ['name' => 'Karataş', 'province' => 1],
            ['name' => 'Karatay', 'province' => 42],
            ['name' => 'Karayazı', 'province' => 25],
            ['name' => 'Karesi', 'province' => 10],
            ['name' => 'Kargı', 'province' => 19],
            ['name' => 'Karkamış', 'province' => 27],
            ['name' => 'Karlıova', 'province' => 12],
            ['name' => 'Karpuzlu', 'province' => 9],
            ['name' => 'Kars', 'province' => 36],
            ['name' => 'Karşıyaka', 'province' => 35],
            ['name' => 'Kartal', 'province' => 34],
            ['name' => 'Kartepe', 'province' => 41],
            ['name' => 'Kastamonu', 'province' => 37],
            ['name' => 'Kaş', 'province' => 7],
            ['name' => 'Kavak', 'province' => 55],
            ['name' => 'Kavaklıdere', 'province' => 48],
            ['name' => 'Kayapınar', 'province' => 21],
            ['name' => 'Kaynarca', 'province' => 54],
            ['name' => 'Kaynaşlı', 'province' => 81],
            ['name' => 'Kazan', 'province' => 6],
            ['name' => 'Kazımkarabekir', 'province' => 70],
            ['name' => 'Keban', 'province' => 23],
            ['name' => 'Keçiborlu', 'province' => 32],
            ['name' => 'Keçiören', 'province' => 6],
            ['name' => 'Keles', 'province' => 16],
            ['name' => 'Kelkit', 'province' => 29],
            ['name' => 'Kemah', 'province' => 24],
            ['name' => 'Kemaliye', 'province' => 24],
            ['name' => 'Kemalpaşa', 'province' => 35],
            ['name' => 'Kemer', 'province' => 7],
            ['name' => 'Kemer', 'province' => 15],
            ['name' => 'Kepez', 'province' => 7],
            ['name' => 'Kepsut', 'province' => 10],
            ['name' => 'Keskin', 'province' => 71],
            ['name' => 'Kestel', 'province' => 16],
            ['name' => 'Keşan', 'province' => 22],
            ['name' => 'Keşap', 'province' => 28],
            ['name' => 'Kıbrıscık', 'province' => 14],
            ['name' => 'Kınık', 'province' => 35],
            ['name' => 'Kırıkhan', 'province' => 31],
            ['name' => 'Kırıkkale', 'province' => 71],
            ['name' => 'Kırkağaç', 'province' => 45],
            ['name' => 'Kırklareli', 'province' => 39],
            ['name' => 'Kırşehir', 'province' => 40],
            ['name' => 'Kızılcahamam', 'province' => 6],
            ['name' => 'Kızılırmak', 'province' => 18],
            ['name' => 'Kızılören', 'province' => 3],
            ['name' => 'Kızıltepe', 'province' => 47],
            ['name' => 'Kiğı', 'province' => 12],
            ['name' => 'Kilimli', 'province' => 67],
            ['name' => 'Kilis', 'province' => 79],
            ['name' => 'Kiraz', 'province' => 35],
            ['name' => 'Kocaali', 'province' => 54],
            ['name' => 'Kocaköy', 'province' => 21],
            ['name' => 'Kocasinan', 'province' => 38],
            ['name' => 'Koçarlı', 'province' => 9],
            ['name' => 'Kofçaz', 'province' => 39],
            ['name' => 'Konak', 'province' => 35],
            ['name' => 'Konyaaltı', 'province' => 7],
            ['name' => 'Korgan', 'province' => 52],
            ['name' => 'Korgun', 'province' => 18],
            ['name' => 'Korkut', 'province' => 49],
            ['name' => 'Korkuteli', 'province' => 7],
            ['name' => 'Kovancılar', 'province' => 23],
            ['name' => 'Koyulhisar', 'province' => 58],
            ['name' => 'Kozaklı', 'province' => 50],
            ['name' => 'Kozan', 'province' => 1],
            ['name' => 'Kozlu', 'province' => 67],
            ['name' => 'Kozluk', 'province' => 72],
            ['name' => 'Köprübaşı', 'province' => 45],
            ['name' => 'Köprübaşı', 'province' => 61],
            ['name' => 'Köprüköy', 'province' => 25],
            ['name' => 'Körfez', 'province' => 41],
            ['name' => 'Köse', 'province' => 29],
            ['name' => 'Köşk', 'province' => 9],
            ['name' => 'Köyceğiz', 'province' => 48],
            ['name' => 'Kula', 'province' => 45],
            ['name' => 'Kulp', 'province' => 21],
            ['name' => 'Kulu', 'province' => 42],
            ['name' => 'Kuluncak', 'province' => 44],
            ['name' => 'Kumlu', 'province' => 31],
            ['name' => 'Kumluca', 'province' => 7],
            ['name' => 'Kumru', 'province' => 52],
            ['name' => 'Kurşunlu', 'province' => 18],
            ['name' => 'Kurtalan', 'province' => 56],
            ['name' => 'Kurucaşile', 'province' => 74],
            ['name' => 'Kuşadası', 'province' => 9],
            ['name' => 'Kuyucak', 'province' => 9],
            ['name' => 'Küçükçekmece', 'province' => 34],
            ['name' => 'Küre', 'province' => 37],
            ['name' => 'Kürtün', 'province' => 29],
            ['name' => 'Kütahya', 'province' => 43],
            ['name' => 'Laçin', 'province' => 19],
            ['name' => 'Ladik', 'province' => 55],
            ['name' => 'Lalapaşa', 'province' => 22],
            ['name' => 'Lapseki', 'province' => 17],
            ['name' => 'Lice', 'province' => 21],
            ['name' => 'Lüleburgaz', 'province' => 39],
            ['name' => 'Maçka', 'province' => 61],
            ['name' => 'Maden', 'province' => 23],
            ['name' => 'Mahmudiye', 'province' => 26],
            ['name' => 'Malazgirt', 'province' => 49],
            ['name' => 'Malkara', 'province' => 59],
            ['name' => 'Maltepe', 'province' => 34],
            ['name' => 'Mamak', 'province' => 6],
            ['name' => 'Manavgat', 'province' => 7],
            ['name' => 'Manyas', 'province' => 10],
            ['name' => 'Marmara', 'province' => 10],
            ['name' => 'Marmaraereğlisi', 'province' => 59],
            ['name' => 'Marmaris', 'province' => 48],
            ['name' => 'Mazgirt', 'province' => 62],
            ['name' => 'Mazıdağı', 'province' => 47],
            ['name' => 'Mecitözü', 'province' => 19],
            ['name' => 'Melikgazi', 'province' => 38],
            ['name' => 'Menderes', 'province' => 35],
            ['name' => 'Menemen', 'province' => 35],
            ['name' => 'Mengen', 'province' => 14],
            ['name' => 'Menteşe', 'province' => 48],
            ['name' => 'Meram', 'province' => 42],
            ['name' => 'Meriç', 'province' => 22],
            ['name' => 'Merkezefendi', 'province' => 20],
            ['name' => 'Merzifon', 'province' => 5],
            ['name' => 'Mesudiye', 'province' => 52],
            ['name' => 'Mezitli', 'province' => 33],
            ['name' => 'Midyat', 'province' => 47],
            ['name' => 'Mihalgazi', 'province' => 26],
            ['name' => 'Mihalıççık', 'province' => 26],
            ['name' => 'Milas', 'province' => 48],
            ['name' => 'Mucur', 'province' => 40],
            ['name' => 'Mudanya', 'province' => 16],
            ['name' => 'Mudurnu', 'province' => 14],
            ['name' => 'Muradiye', 'province' => 65],
            ['name' => 'Muratlı', 'province' => 59],
            ['name' => 'Muratpaşa', 'province' => 7],
            ['name' => 'Murgul', 'province' => 8],
            ['name' => 'Musabeyli', 'province' => 79],
            ['name' => 'Mustafakemalpaşa', 'province' => 16],
            ['name' => 'Muş', 'province' => 49],
            ['name' => 'Mut', 'province' => 33],
            ['name' => 'Mutki', 'province' => 13],
            ['name' => 'Nallıhan', 'province' => 6],
            ['name' => 'Narlıdere', 'province' => 35],
            ['name' => 'Narman', 'province' => 25],
            ['name' => 'Nazımiye', 'province' => 62],
            ['name' => 'Nazilli', 'province' => 9],
            ['name' => 'Nevşehir', 'province' => 50],
            ['name' => 'Niğde', 'province' => 51],
            ['name' => 'Niksar', 'province' => 60],
            ['name' => 'Nilüfer', 'province' => 16],
            ['name' => 'Nizip', 'province' => 27],
            ['name' => 'Nurdağı', 'province' => 27],
            ['name' => 'Nurhak', 'province' => 46],
            ['name' => 'Nusaybin', 'province' => 47],
            ['name' => 'Odunpazarı', 'province' => 26],
            ['name' => 'Of', 'province' => 61],
            ['name' => 'Oğuzeli', 'province' => 27],
            ['name' => 'Oğuzlar', 'province' => 19],
            ['name' => 'Oltu', 'province' => 25],
            ['name' => 'Olur', 'province' => 25],
            ['name' => 'Ondokuzmayıs', 'province' => 55],
            ['name' => 'Onikişubat', 'province' => 46],
            ['name' => 'Orhaneli', 'province' => 16],
            ['name' => 'Orhangazi', 'province' => 16],
            ['name' => 'Orta', 'province' => 18],
            ['name' => 'Ortaca', 'province' => 48],
            ['name' => 'Ortahisar', 'province' => 61],
            ['name' => 'Ortaköy', 'province' => 68],
            ['name' => 'Ortaköy', 'province' => 19],
            ['name' => 'Osmancık', 'province' => 19],
            ['name' => 'Osmaneli', 'province' => 11],
            ['name' => 'Osmangazi', 'province' => 16],
            ['name' => 'Osmaniye', 'province' => 80],
            ['name' => 'Otlukbeli', 'province' => 24],
            ['name' => 'Ovacık', 'province' => 78],
            ['name' => 'Ovacık', 'province' => 62],
            ['name' => 'Ödemiş', 'province' => 35],
            ['name' => 'Ömerli', 'province' => 47],
            ['name' => 'Özalp', 'province' => 65],
            ['name' => 'Özvatan', 'province' => 38],
            ['name' => 'Palandöken', 'province' => 25],
            ['name' => 'Palu', 'province' => 23],
            ['name' => 'Pamukkale', 'province' => 20],
            ['name' => 'Pamukova', 'province' => 54],
            ['name' => 'Pasinler', 'province' => 25],
            ['name' => 'Patnos', 'province' => 4],
            ['name' => 'Payas', 'province' => 31],
            ['name' => 'Pazar', 'province' => 53],
            ['name' => 'Pazar', 'province' => 60],
            ['name' => 'Pazarcık', 'province' => 46],
            ['name' => 'Pazarlar', 'province' => 43],
            ['name' => 'Pazaryeri', 'province' => 11],
            ['name' => 'Pazaryolu', 'province' => 25],
            ['name' => 'Pehlivanköy', 'province' => 39],
            ['name' => 'Pendik', 'province' => 34],
            ['name' => 'Perşembe', 'province' => 52],
            ['name' => 'Pertek', 'province' => 62],
            ['name' => 'Pervari', 'province' => 56],
            ['name' => 'Pınarbaşı', 'province' => 37],
            ['name' => 'Pınarbaşı', 'province' => 38],
            ['name' => 'Pınarhisar', 'province' => 39],
            ['name' => 'Piraziz', 'province' => 28],
            ['name' => 'Polateli', 'province' => 79],
            ['name' => 'Polatlı', 'province' => 6],
            ['name' => 'Posof', 'province' => 75],
            ['name' => 'Pozantı', 'province' => 1],
            ['name' => 'Pursaklar', 'province' => 6],
            ['name' => 'Pülümür', 'province' => 62],
            ['name' => 'Pütürge', 'province' => 44],
            ['name' => 'Refahiye', 'province' => 24],
            ['name' => 'Reşadiye', 'province' => 60],
            ['name' => 'Reyhanlı', 'province' => 31],
            ['name' => 'Rize', 'province' => 53],
            ['name' => 'Safranbolu', 'province' => 78],
            ['name' => 'Saimbeyli', 'province' => 1],
            ['name' => 'Salıpazarı', 'province' => 55],
            ['name' => 'Salihli', 'province' => 45],
            ['name' => 'Samandağ', 'province' => 31],
            ['name' => 'Samsat', 'province' => 2],
            ['name' => 'Sancaktepe', 'province' => 34],
            ['name' => 'Sandıklı', 'province' => 3],
            ['name' => 'Sapanca', 'province' => 54],
            ['name' => 'Saray', 'province' => 59],
            ['name' => 'Saray', 'province' => 65],
            ['name' => 'Saraydüzü', 'province' => 57],
            ['name' => 'Saraykent', 'province' => 66],
            ['name' => 'Sarayköy', 'province' => 20],
            ['name' => 'Sarayönü', 'province' => 42],
            ['name' => 'Sarıcakaya', 'province' => 26],
            ['name' => 'Sarıçam', 'province' => 1],
            ['name' => 'Sarıgöl', 'province' => 45],
            ['name' => 'Sarıkamış', 'province' => 36],
            ['name' => 'Sarıkaya', 'province' => 66],
            ['name' => 'Sarıoğlan', 'province' => 38],
            ['name' => 'Sarıveliler', 'province' => 70],
            ['name' => 'Sarıyahşi', 'province' => 68],
            ['name' => 'Sarıyer', 'province' => 34],
            ['name' => 'Sarız', 'province' => 38],
            ['name' => 'Saruhanlı', 'province' => 45],
            ['name' => 'Sason', 'province' => 72],
            ['name' => 'Savaştepe', 'province' => 10],
            ['name' => 'Savur', 'province' => 47],
            ['name' => 'Seben', 'province' => 14],
            ['name' => 'Seferihisar', 'province' => 35],
            ['name' => 'Selçuk', 'province' => 35],
            ['name' => 'Selçuklu', 'province' => 42],
            ['name' => 'Selendi', 'province' => 45],
            ['name' => 'Selim', 'province' => 36],
            ['name' => 'Senirkent', 'province' => 32],
            ['name' => 'Serdivan', 'province' => 54],
            ['name' => 'Serik', 'province' => 7],
            ['name' => 'Serinhisar', 'province' => 20],
            ['name' => 'Seydikemer', 'province' => 48],
            ['name' => 'Seydiler', 'province' => 37],
            ['name' => 'Seydişehir', 'province' => 42],
            ['name' => 'Seyhan', 'province' => 1],
            ['name' => 'Seyitgazi', 'province' => 26],
            ['name' => 'Sındırgı', 'province' => 10],
            ['name' => 'Siirt', 'province' => 56],
            ['name' => 'Silifke', 'province' => 33],
            ['name' => 'Silivri', 'province' => 34],
            ['name' => 'Silopi', 'province' => 73],
            ['name' => 'Silvan', 'province' => 21],
            ['name' => 'Simav', 'province' => 43],
            ['name' => 'Sinanpaşa', 'province' => 3],
            ['name' => 'Sincan', 'province' => 6],
            ['name' => 'Sincik', 'province' => 2],
            ['name' => 'Sinop', 'province' => 57],
            ['name' => 'Sivas', 'province' => 58],
            ['name' => 'Sivaslı', 'province' => 64],
            ['name' => 'Siverek', 'province' => 63],
            ['name' => 'Sivrice', 'province' => 23],
            ['name' => 'Sivrihisar', 'province' => 26],
            ['name' => 'Solhan', 'province' => 12],
            ['name' => 'Soma', 'province' => 45],
            ['name' => 'Sorgun', 'province' => 66],
            ['name' => 'Söğüt', 'province' => 11],
            ['name' => 'Söğütlü', 'province' => 54],
            ['name' => 'Söke', 'province' => 9],
            ['name' => 'Sulakyurt', 'province' => 71],
            ['name' => 'Sultanbeyli', 'province' => 34],
            ['name' => 'Sultandağı', 'province' => 3],
            ['name' => 'Sultangazi', 'province' => 34],
            ['name' => 'Sultanhisar', 'province' => 9],
            ['name' => 'Suluova', 'province' => 5],
            ['name' => 'Sulusaray', 'province' => 60],
            ['name' => 'Sumbas', 'province' => 80],
            ['name' => 'Sungurlu', 'province' => 19],
            ['name' => 'Sur', 'province' => 21],
            ['name' => 'Suruç', 'province' => 63],
            ['name' => 'Susurluk', 'province' => 10],
            ['name' => 'Susuz', 'province' => 36],
            ['name' => 'Suşehri', 'province' => 58],
            ['name' => 'Süleymanpaşa', 'province' => 59],
            ['name' => 'Süloğlu', 'province' => 22],
            ['name' => 'Sürmene', 'province' => 61],
            ['name' => 'Sütçüler', 'province' => 32],
            ['name' => 'Şabanözü', 'province' => 18],
            ['name' => 'Şahinbey', 'province' => 27],
            ['name' => 'Şalpazarı', 'province' => 61],
            ['name' => 'Şaphane', 'province' => 43],
            ['name' => 'Şarkışla', 'province' => 58],
            ['name' => 'Şarkikaraağaç', 'province' => 32],
            ['name' => 'Şarköy', 'province' => 59],
            ['name' => 'Şavşat', 'province' => 8],
            ['name' => 'Şebinkarahisar', 'province' => 28],
            ['name' => 'Şefaatli', 'province' => 66],
            ['name' => 'Şehitkamil', 'province' => 27],
            ['name' => 'Şehzadeler', 'province' => 45],
            ['name' => 'Şemdinli', 'province' => 30],
            ['name' => 'Şenkaya', 'province' => 25],
            ['name' => 'Şenpazar', 'province' => 37],
            ['name' => 'Şereflikoçhisar', 'province' => 6],
            ['name' => 'Şırnak', 'province' => 73],
            ['name' => 'Şile', 'province' => 34],
            ['name' => 'Şiran', 'province' => 29],
            ['name' => 'Şirvan', 'province' => 56],
            ['name' => 'Şişli', 'province' => 34],
            ['name' => 'Şuhut', 'province' => 3],
            ['name' => 'Talas', 'province' => 38],
            ['name' => 'Taraklı', 'province' => 54],
            ['name' => 'Tarsus', 'province' => 33],
            ['name' => 'Taşkent', 'province' => 42],
            ['name' => 'Taşköprü', 'province' => 37],
            ['name' => 'Taşlıçay', 'province' => 4],
            ['name' => 'Taşova', 'province' => 5],
            ['name' => 'Tatvan', 'province' => 13],
            ['name' => 'Tavas', 'province' => 20],
            ['name' => 'Tavşanlı', 'province' => 43],
            ['name' => 'Tefenni', 'province' => 15],
            ['name' => 'Tekkeköy', 'province' => 55],
            ['name' => 'Tekman', 'province' => 25],
            ['name' => 'Tepebaşı', 'province' => 26],
            ['name' => 'Tercan', 'province' => 24],
            ['name' => 'Termal', 'province' => 77],
            ['name' => 'Terme', 'province' => 55],
            ['name' => 'Tillo', 'province' => 56],
            ['name' => 'Tire', 'province' => 35],
            ['name' => 'Tirebolu', 'province' => 28],
            ['name' => 'Tokat', 'province' => 60],
            ['name' => 'Tomarza', 'province' => 38],
            ['name' => 'Tonya', 'province' => 61],
            ['name' => 'Toprakkale', 'province' => 80],
            ['name' => 'Torbalı', 'province' => 35],
            ['name' => 'Toroslar', 'province' => 33],
            ['name' => 'Tortum', 'province' => 25],
            ['name' => 'Torul', 'province' => 29],
            ['name' => 'Tosya', 'province' => 37],
            ['name' => 'Tufanbeyli', 'province' => 1],
            ['name' => 'Tunceli', 'province' => 62],
            ['name' => 'Turgutlu', 'province' => 45],
            ['name' => 'Turhal', 'province' => 60],
            ['name' => 'Tuşba', 'province' => 65],
            ['name' => 'Tut', 'province' => 2],
            ['name' => 'Tutak', 'province' => 4],
            ['name' => 'Tuzla', 'province' => 34],
            ['name' => 'Tuzluca', 'province' => 76],
            ['name' => 'Tuzlukçu', 'province' => 42],
            ['name' => 'Türkeli', 'province' => 57],
            ['name' => 'Türkoğlu', 'province' => 46],
            ['name' => 'Uğurludağ', 'province' => 19],
            ['name' => 'Ula', 'province' => 48],
            ['name' => 'Ulaş', 'province' => 58],
            ['name' => 'Ulubey', 'province' => 52],
            ['name' => 'Ulubey', 'province' => 64],
            ['name' => 'Uluborlu', 'province' => 32],
            ['name' => 'Uludere', 'province' => 73],
            ['name' => 'Ulukışla', 'province' => 51],
            ['name' => 'Ulus', 'province' => 74],
            ['name' => 'Urla', 'province' => 35],
            ['name' => 'Uşak', 'province' => 64],
            ['name' => 'Uzundere', 'province' => 25],
            ['name' => 'Uzunköprü', 'province' => 22],
            ['name' => 'Ümraniye', 'province' => 34],
            ['name' => 'Ünye', 'province' => 52],
            ['name' => 'Ürgüp', 'province' => 50],
            ['name' => 'Üsküdar', 'province' => 34],
            ['name' => 'Üzümlü', 'province' => 24],
            ['name' => 'Vakfıkebir', 'province' => 61],
            ['name' => 'Varto', 'province' => 49],
            ['name' => 'Vezirköprü', 'province' => 55],
            ['name' => 'Viranşehir', 'province' => 63],
            ['name' => 'Vize', 'province' => 39],
            ['name' => 'Yağlıdere', 'province' => 28],
            ['name' => 'Yahşihan', 'province' => 71],
            ['name' => 'Yahyalı', 'province' => 38],
            ['name' => 'Yakakent', 'province' => 55],
            ['name' => 'Yakutiye', 'province' => 25],
            ['name' => 'Yalıhüyük', 'province' => 42],
            ['name' => 'Yalova', 'province' => 77],
            ['name' => 'Yalvaç', 'province' => 32],
            ['name' => 'Yapraklı', 'province' => 18],
            ['name' => 'Yatağan', 'province' => 48],
            ['name' => 'Yavuzeli', 'province' => 27],
            ['name' => 'Yayladağı', 'province' => 31],
            ['name' => 'Yayladere', 'province' => 12],
            ['name' => 'Yazıhan', 'province' => 44],
            ['name' => 'Yedisu', 'province' => 12],
            ['name' => 'Yenice', 'province' => 17],
            ['name' => 'Yenice', 'province' => 78],
            ['name' => 'Yeniçağa', 'province' => 14],
            ['name' => 'Yenifakılı', 'province' => 66],
            ['name' => 'Yenimahalle', 'province' => 6],
            ['name' => 'Yenipazar', 'province' => 9],
            ['name' => 'Yenipazar', 'province' => 11],
            ['name' => 'Yenişarbademli', 'province' => 32],
            ['name' => 'Yenişehir', 'province' => 16],
            ['name' => 'Yenişehir', 'province' => 21],
            ['name' => 'Yenişehir', 'province' => 33],
            ['name' => 'Yerköy', 'province' => 66],
            ['name' => 'Yeşilhisar', 'province' => 38],
            ['name' => 'Yeşilli', 'province' => 47],
            ['name' => 'Yeşilova', 'province' => 15],
            ['name' => 'Yeşilyurt', 'province' => 44],
            ['name' => 'Yeşilyurt', 'province' => 60],
            ['name' => 'Yığılca', 'province' => 81],
            ['name' => 'Yıldırım', 'province' => 16],
            ['name' => 'Yıldızeli', 'province' => 58],
            ['name' => 'Yomra', 'province' => 61],
            ['name' => 'Yozgat', 'province' => 66],
            ['name' => 'Yumurtalık', 'province' => 1],
            ['name' => 'Yunak', 'province' => 42],
            ['name' => 'Yunusemre', 'province' => 45],
            ['name' => 'Yusufeli', 'province' => 8],
            ['name' => 'Yüksekova', 'province' => 30],
            ['name' => 'Yüreğir', 'province' => 1],
            ['name' => 'Zara', 'province' => 58],
            ['name' => 'Zeytinburnu', 'province' => 34],
            ['name' => 'Zile', 'province' => 60],
            ['name' => 'Zonguldak', 'province' => 67],
            ['name' => 'Kemalpaşa', 'province' => 8],
            ['name' => 'Sultanhanı', 'province' => 68]
        ]);

        $provinces->each(function ($name, $key) use ($counties) {
            $province = \App\Models\Province::create([
                'name' => $name
            ]);

            $counties->where('province', $key)->each(function ($data) use ($province) {
                $province->counties()->create([
                    'name' => $data['name']
                ]);
            });
        });
    }
}
